"""Inicial

Revision ID: 0394e4663cd1
Revises: 
Create Date: 2025-08-23 19:03:59.233867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0394e4663cd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etiquetas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('curriculums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('fecha_subida', sa.Date(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_empresa', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_empresa')
    )
    op.create_table('curriculums_etiquetas',
    sa.Column('curriculums_id', sa.Integer(), nullable=False),
    sa.Column('etiquetas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curriculums_id'], ['curriculums.id'], ),
    sa.ForeignKeyConstraint(['etiquetas_id'], ['etiquetas.id'], ),
    sa.PrimaryKeyConstraint('curriculums_id', 'etiquetas_id')
    )
    op.create_table('empresas_etiquetas',
    sa.Column('empresas_id', sa.Integer(), nullable=False),
    sa.Column('etiquetas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresas_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['etiquetas_id'], ['etiquetas.id'], ),
    sa.PrimaryKeyConstraint('empresas_id', 'etiquetas_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empresas_etiquetas')
    op.drop_table('curriculums_etiquetas')
    op.drop_table('empresas')
    op.drop_table('curriculums')
    op.drop_table('usuario')
    op.drop_table('etiquetas')
    # ### end Alembic commands ###
