"""Agregar tabla de etiquetas y relacion con postulantes

Revision ID: 5db83dd25d7c
Revises: bfd564af7c7f
Create Date: 2025-09-11 16:45:22.899540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db83dd25d7c'
down_revision = 'bfd564af7c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etiqueta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('postulante_etiquetas',
    sa.Column('postulante_id', sa.Integer(), nullable=False),
    sa.Column('etiqueta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etiqueta_id'], ['etiqueta.id'], ),
    sa.ForeignKeyConstraint(['postulante_id'], ['postulante_registro.id'], ),
    sa.PrimaryKeyConstraint('postulante_id', 'etiqueta_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postulante_etiquetas')
    op.drop_table('etiqueta')
    # ### end Alembic commands ###
